scrape_configs:
  - job_name: 'kubernetes-pods-nodejs'
    kubernetes_sd_configs:
      - role: pod  # Discover and scrape metrics from all pods
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        target_label: app
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_container_name]
        target_label: container
      - source_labels: [__meta_kubernetes_pod_container_name]
        target_label: container
        regex: 'nodejs.*'  # Match containers related to Node.js apps
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        regex: 'http_requests_total|http_request_duration_seconds'
